### ISSUE TITLE
Invalid API key and can not access the settings again. 

### ISSUE THREAD

**Issue by marcerebrum** [ebizmarts/magento2-mandrill#1]
Hello,

See attached images.

When insert api key occurred this error.

"Invalid API key"

I can not access module settings again.

Store > Configuration > MageMonkey > Mandrill

![captura de tela de 2015-04-23 22 23 12](https://cloud.githubusercontent.com/assets/2263217/7310756/e351ec60-ea07-11e4-8417-d91a2ec90a8d.png)
![captura de tela de 2015-04-23 22 23 20](https://cloud.githubusercontent.com/assets/2263217/7310758/e36bfe34-ea07-11e4-90f2-8e87b341a5eb.png)
![captura de tela de 2015-04-23 22 23 35](https://cloud.githubusercontent.com/assets/2263217/7310757/e35a3000-ea07-11e4-9549-f4926ab04ec7.png)

Cheers,

Marcelo Amorim

**Comment by gonzaloebiz** [comment]
What is your MageMonkey version?
I'm trying to reproduce this, and i can't. The fast way is, delete the entry in core_config_data for path = 'mandrill/general/apikey'
Keep in mind, you must enter the mandrill api key,not the mailchimp api key

Best

**Comment by marcerebrum** [comment]
Hello,

See errors after include email in field subscribe.

![captura de tela de 2015-05-04 21 06 08](https://cloud.githubusercontent.com/assets/2263217/7465188/9324b1ca-f2a2-11e4-8dfb-48b651354ec4.png)
![captura de tela de 2015-05-04 21 06 24](https://cloud.githubusercontent.com/assets/2263217/7465187/932216cc-f2a2-11e4-908d-5d0bf91d9dc3.png)

**Comment by gonzaloebiz** [comment]
Hi,

the extension is waiting  a magento2 pr https://github.com/magento/magento2/pull/1183
We modify some classes in the core, so you must wait until the pr is approved

Best
