### ISSUE TITLE
Even if disabled causes error when signing up after checkout

### ISSUE THREAD

**Issue by maderlock** [ebizmarts/magento2-mandrill#10]
Having installed the module in 2.0.4, I completed the checkout and clicked on the button to create a new account. I get the following error:

```
Notice: Trying to get property of non-object in .../vendor/ebizmarts/magento2-mandrill/Model/Transport.php on line 81
```

It looks like Mandrill is trying to send the email even though it's disabled, and complaining because if there is no API key set then it never creates a Mandrill object for sending.

**Comment by maderlock** [comment]
Taking a look at this method, it replaces the normal class via DI. That would not be an issue, but when adding in the scopeConfig into the constructor it appears that the Message class manually initialises the Transport class rather than using DI, so additional parameters such as the scopeConfig and/or a fall-back Transport class are not automatically filled by DI. It would be best to remove this manual instantiation too.

**Comment by maderlock** [comment]
Any progress?

**Comment by centerax** [comment]
Hi @maderlock 

Apologies for the delay, we will take a look and get back to you

**Comment by gonzaloebiz** [comment]
Hi @maderlock 

you have the lib mandrill/mandrill installed?
Try running

composer require mandrill/mandrill

Best

**Comment by maderlock** [comment]
ebizmarts/magento2-mandrill has mandrill/mandrill as a requirement so this is installed automatically when ebizmarts/magento2-mandrill is pulled in via composer.

e.g.

```
 composer require ebizmarts/magento2-mandrill
```

Outcome:

```
  - Installing mandrill/mandrill (1.0.55)
    Loading from cache

  - Installing ebizmarts/magento2-mandrill (3.0.5)
    Loading from cache
```

**Comment by maderlock** [comment]
Any progress?

**Comment by maderlock** [comment]
Any progress?

**Comment by maderlock** [comment]
Hello? Anyone there? This is a major bug. Does anyone care?

**Comment by SantiParagarino** [comment]
Hello @maderlock,

Sorry for the delay. I will try to take a look at this today.

Regards.

**Comment by HellgaM** [comment]
Hi, is there any progress?

**Comment by SantiParagarino** [comment]
Hello,

Sorry for the delay. This should be solved in the latest version of the extension.
