### ISSUE TITLE
Order Emails Not Sending 2.2.8 CE - Test Email Works

### ISSUE THREAD

**Issue by nickpiro** [ebizmarts/magento2-mandrill#105]
We're using Mandrill 3.0.13 on Magento 2.2.8. We just upgraded Magento from 2.2.5 and Mandrill was working perfectly fine.

**To Reproduce**
1. Create Order
2. Email Doesn't Send

**Expected behavior**
Order email should send, it doesn't

The only emails sending so far as I can see are Password Reset, New Account Registered, etc

**Comment by evs-xsarus** [comment]
This is still happening, I get this error:

PHP Fatal error:  Uncaught Error: Call to undefined method Magento\\Framework\\Mail\\Message::getFrom() in /home/mag/vendor/ebizmarts/magento2-mandrill/Model/Message.php:102

Stack trace:
```
#0 /home/mag/vendor/magepal/magento2-gmailsmtpapp/Plugin/Mail/TransportPlugin.php(48): Ebizmarts\\Mandrill\\Model\\Message->getFrom()
#1 /home/mag/vendor/magepal/magento2-gmailsmtpapp/Plugin/Mail/TransportPlugin.php(30): MagePal\\GmailSmtpApp\\Plugin\\Mail\\TransportPlugin->sendSmtpMessage(Object(Ebizmarts\\Mandrill\\Model\\Message\\Interceptor))
#2 /home/mag/vendor/magento/framework/Interception/Interceptor.php(135): MagePal\\GmailSmtpApp\\Plugin\\Mail\\TransportPlugin->aroundSendMessage(Object(Magento\\Email\\Model\\Transport\\Interceptor), Object(Closure))
#3 /home/mag/vendor/dotmailer/dotmailer-magento2-extension/Plugin/TransportPlugin.php(75): Magento\\Email\\Model\\Transport\\Interceptor->Magento\\Framework\\Interception\\{...\n
```
