### ISSUE TITLE
Version 3.2.7 Not Working with Magento 2.2.8

### ISSUE THREAD

**Issue by perryholden** [ebizmarts/magento2-mandrill#106]
With Magento 2.2.8, transactional and test emails no longer send.

### Preconditions

1. Magento Commerce 2.2.8
2. PHP 7.1
4. Ebizmarts Mandrill v. 3.2.17

### Steps to reproduce

1. Login to the admin.
2. Navigate to the config settings.
3. Enter an email address, and click "Send Test Email".

### Expected result

* An email will be sent.

### Actual result

* I get an error message: "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

### Additional Details

* This also happens when sending an order email.
* This is due to \Magento\Framework\Mail\Message::setFrom() being deprecated in Magento 2.2.8.
* In \Ebizmarts\Mandrill\Model\Transport::sendMessage(), the `from_name` and the `from_email` are blank, thus you get an invalid sender error.
* You need to create a new method in \Ebizmarts\Mandrill\Model\Message
* This composer patch fixes the issue:

```
diff --git a/Model/Message.php b/Model/Message.php
index 2bfe9fc..7a71ce1 100644
--- a/Model/Message.php
+++ b/Model/Message.php
@@ -78,6 +78,12 @@ class Message extends \Magento\Framework\Mail\Message implements \Magento\Framew
     }
 
     public function setFrom($fromAddress, $name = null)
+    {
+        $this->setFromAddress($fromAddress, $name);
+        return $this;
+    }
+
+    public function setFromAddress($fromAddress, $name = null)
     {
         if ($this->mandrillHelper->isMandrillEnabled()) {
             $this->mandrillFrom      = $fromAddress;

```

**Comment by gonzaloebiz** [comment]
Hi @dewayneholden 

we wrote a new extension for Mandrill for magento >= 2.2.8
Remove this extension (composer remove ebizmarts/magento2-mandrill) and try https://github.com/ebizmarts/magento2-mandrill-smtp

Best
