### ISSUE TITLE
Magento 2.3.1 Invalid Sender (Fix)

### ISSUE THREAD

**Issue by Lycanite** [ebizmarts/magento2-mandrill#108]
After upgrading to Magento 2.3.1 from 2.3 the "Email sending failed: invalid-sender" issue returned, this is using 3.3.16.

I've managed to fix this be renaming the function "setFrom" to "setFromAddress in the Ebizmarts\Mandrill\Model\Message class so that it matches what the Magento\Framework\Mail\Template\TransportBuilder class is calling in its new setFromByScope method.

**Comment by alinalexandru** [comment]
I will prepare a Pull Request to fix for 2.3.1 and 2.2.9

**Comment by gonzaloebiz** [comment]
Hi @alinalexandru 

we wrote a new extension for Mandrill for magento >= 2.2.8
Remove this extension (composer remove ebizmarts/magento2-mandrill) and try https://github.com/ebizmarts/magento2-mandrill-smtp

Best

**Comment by andrewkett** [comment]
Is this module deprecated in favour of the SMTP one then?

**Comment by gonzaloebiz** [comment]
yes, for magento  >= 2.2.8

**Comment by andrewkett** [comment]
Can I suggest you update the readme to reflect that?

**Comment by gonzaloebiz** [comment]
sure
