### ISSUE TITLE
Fatal error: Class 'Mandrill' not found in app/code/Ebizmarts/Mandrill/Model/Api/Mandrill.php on line 31

### ISSUE THREAD

**Issue by rajajitesh** [ebizmarts/magento2-mandrill#11]
I have recently installed Mage Money from store.ebizmarts.com, but I have been getting this error whenever I try to add my mail chimp API key.

**Comment by gonzaloebiz** [comment]
Hi @rajajitesh,

you have Mandrill installed?
Try to run composer require mandrill/mandrill

Best

**Comment by rajajitesh** [comment]
@gonzaloebiz  Thanks. It worked now.

**Comment by tuyennn** [comment]
This must be put to README.md for leading instruction.
