### ISSUE TITLE
Mandrill stops working on Magento 2.3.2

### ISSUE THREAD

**Issue by jaredchu** [ebizmarts/magento2-mandrill#115]
**Describe the bug**
Like the title, it's working on Magento 2.3.0 but 2.3.2
Magento version: 2.3.2
magento2-mandrill: 3.3.16

**To Reproduce**
1. Go to Admin > Store > Configuration > Mailchimp > Mandrill
2. Click on 'Send Test Email'

**Expected behavior**
The email will be send

**Additional context**
Email stops working at all, not only the test email

**Comment by gonzaloebiz** [comment]
Hi @jaredchu 

we wrote a new extension for Mandrill for magento >= 2.2.8
Remove this extension (composer remove ebizmarts/magento2-mandrill) and try https://github.com/ebizmarts/magento2-mandrill-smtp

Best
