### ISSUE TITLE
Error thrown in Magento 2.3.1: Call to a member function toString() on string

### ISSUE THREAD

**Issue by wisehuang** [ebizmarts/magento2-mandrill#117]
**Describe the bug**
In branch 2.3-develop, class: Model/Message.php line 74: return $this->mandrillBodyText->toString();

It will throw an uncaught error: Call to a member function toString() on string in /var/log/php-fpm/www-error.log

The full error message will be:
`PHP Fatal error:  Uncaught Error: Call to a member function toString() on string in /usr/share/nginx/html/magento2/vendor/ebizmarts/magento2-mandrill/Model/Message.php:76
Stack trace:
#0 /usr/share/nginx/html/magento2/vendor/magento/module-email/Model/Transport.php(90): Ebizmarts\Mandrill\Model\Message->getRawMessage()
#1 /usr/share/nginx/html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Email\Model\Transport->sendMessage()
#2 /usr/share/nginx/html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Email\Model\Transport\Interceptor->___callParent('sendMessage', Array)
#3 /usr/share/nginx/html/magento2/vendor/magento/module-email/Model/Mail/TransportInterfacePlugin.php(48): Magento\Email\Model\Transport\Interceptor->Magento\Framework\Interception\{closure}()
#4 /usr/share/nginx/html/magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Email\Model\Mail\TransportInterfacePlugin->aroundSendMessage(Object(Magento\Email\Model\Transport\Interceptor), Obj in /usr/share/nginx/html/magento2/vendor/ebizmarts/magento2-mandrill/Model/Message.php on line 76`

**To Reproduce**
1. Go to 'Add New Customer'
2. Fill in all required data to add a new customer
3. Save
4. There will be an error and respose HTTP status code 500 in Magento frontend

**Expected behavior**
Add new customer successfully

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.5
 - Browser: Chrome 
 - Version: 75.0.3770.100 (Official Build) (64-bit)

**Additional context**
We can fix this issue by removing toString(), just: `return $this->mandrillBodyText;`

**Comment by gonzaloebiz** [comment]
Hi @wisehuang 

we wrote a new extension for Mandrill for magento >= 2.2.8
Remove this extension (composer remove ebizmarts/magento2-mandrill) and try https://github.com/ebizmarts/magento2-mandrill-smtp

Best
