### ISSUE TITLE
from_name and from_email are set to null on Magento2.3.1

### ISSUE THREAD

**Issue by syedsaleem086** [ebizmarts/magento2-mandrill#118]
**Describe the bug**
from_name and from_email is always null even if it is configured in Magento backend

**To Reproduce**
1. Install Magento2.3.1 (Working on magento2.3.0)
2. Install Mandrill using composer
3. Configure store email address on Magento backend
4. Test send email
5. Login to mandrill dashboard -> API Logs (You will notice there is no from_name and from_email is set)

**Expected behavior**
from_name and from_email should set as per configured in Magento backend

**Server details:**
 - Ubuntu
 - PHP 7.2-FPM and Nginx

**Comment by gonzaloebiz** [comment]
hi @syedsaleem086 

thanks for the feedback, but for magento >= 2.2.8 you must use https://github.com/ebizmarts/magento2-mandrill-smtp

Best
