### ISSUE TITLE
mandril install by putty show error

### ISSUE THREAD

**Issue by nitaipanda** [ebizmarts/magento2-mandrill#119]
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/framework 101.0.7 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - magento/framework 101.0.7 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.19) does not satisfy that requirement.
    - magento/framework 101.0.7 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - Installation request for magento/framework (locked at 101.0.7) -> satisfiable by magento/framework[101.0.7].

  To enable extensions, verify that they are enabled in your .ini files:
    - /opt/cpanel/ea-php72/root/etc/php.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-bcmath.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-calendar.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-ctype.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-curl.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-dom.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-fileinfo.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-ftp.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-gd.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-iconv.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-imap.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-json.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-mbstring.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-mysqlnd.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-pdo.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-phar.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-posix.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-simplexml.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-soap.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-sockets.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-sqlite3.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-tokenizer.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-xml.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-xmlwriter.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-xsl.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-zip.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/30-mysqli.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/30-pdo_mysql.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/30-pdo_sqlite.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/30-wddx.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/30-xmlreader.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/zzzzzzz-pecl.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by nitaipanda** [comment]
please give solution

**Comment by nitaipanda** [comment]
![image](https://user-images.githubusercontent.com/20333565/61869008-4688be80-aef8-11e9-86c1-437c19f9b465.png)

**Comment by gonzaloebiz** [comment]
What version of magento do you have?
Keep in mind this requirements https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html
If you have magento 2.2 is not compatible with php 7.2

Best
