### ISSUE TITLE
Cannot save configuration

### ISSUE THREAD

**Issue by avra911** [ebizmarts/magento2-mandrill#12]
When using this field, there is a javascript error in console and a loading gif appear and does not save the data:

```
<field id="account_details" translate="label" type="textarea" sortOrder="40" ...>
  <label>Account Details</label>
  <frontend_model>Ebizmarts\Mandrill\Block\Adminhtml\System\Config\...</frontend_model>
  <source_model>Ebizmarts\Mandrill\Model\Config\Source\Details</source_model>
  <depends>
    <field id="*/*/active">1</field>
  </depends>
</field>
```

Without this field it works!

See: https://nimbus.everhelper.me/client/notes/share/483842/b3gsid4kyazz50t2bwxi
Same thing on magento 2.0.4 as well as on 2.0.7.

**Comment by avra911** [comment]
Sorry, we had some corrupted files

**Comment by avra911** [comment]
I noticed that just removing this part of the field declaration:

```
<depends>
  <field id="*/*/active">1</field>
</depends>
```

makes the save working.

**Comment by gonzaloebiz** [comment]
You have the mandrill/mandrill lib installed?
Run
composer require mandrill/mandrill

**Comment by avra911** [comment]
Isn't that installed by ebizmarts requirements automatically?

```
Using version ^1.0 for mandrill/mandrill
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Writing lock file
Generating autoload files
```

Why did you closed the issue @gonzaloebiz ?

**Comment by avra911** [comment]
Isn't installed by ebizmarts composer as requirements?

```
$ composer require mandrill/mandrill
Using version ^1.0 for mandrill/mandrill
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. ...
Writing lock file
Generating autoload files
```

```
magento@deploy:~/htdocs$ composer require ebizmarts/magento2-mandrill ^3.0.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing mandrill/mandrill (1.0.55)
    Downloading: 100%         

  - Installing ebizmarts/magento2-mandrill (3.0.5)
    Downloading: 100%    
```

It is an UI problem, most probably a magento bug which affects you. Thought you have any ideas.
Please read again my test case, because I edited a few times.

I will also created a fresh installation of magento and come back to you!

Best,
R

**Comment by avra911** [comment]
Alright, here are updates on a fresh installation.

The save button works, however the field `account_details` is not hidden/show on enable/disable option select. Same for `mandrill_general_test_email` field.

Best,
Razvan

**Comment by avra911** [comment]
moved to new issue: https://github.com/ebizmarts/magento2-mandrill/issues/13

thanks,
R
