### ISSUE TITLE
Mandrill Config Not Showing in Admin Panel

### ISSUE THREAD

**Issue by vithefiddler** [ebizmarts/magento2-mandrill#120]
**Describe the bug**
Mandrill Config Not Showing in Store Configuration Admin Panel

**To Reproduce**
1. Go to 'Stores -> Configuration'
2. Click on 'Anything' - I can't find an item in there for Mandrill. I have looked in any other area in the admin panel that seems to remotely relate with no luck. I have looked through my logs for a related error with no luck. If I'm looking in the wrong area, please let me know. 

**Expected behavior**
The Mailchimp logo and configuration is in this area, so I would expect the configuration for Mandrill to be there as well.

**Screenshots**
<img width="1920" alt="Screenshot 2019-08-09 00 31 48" src="https://user-images.githubusercontent.com/191704/62758954-1df6dd80-ba3d-11e9-94e1-f36f38fc6145.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 75.0.3770.142 (Official Build) (64-bit)

**Additional context**
We have version 3.2.17 installed.

**Comment by gonzaloebiz** [comment]
Hi @vithefiddler 

what version of magento do you have?
Click on the Freddie icon
![image](https://user-images.githubusercontent.com/6222792/62778716-7c48ae00-ba87-11e9-850a-e8a9d67a20f8.png)

Or expand the Mailchimp menu item

![image](https://user-images.githubusercontent.com/6222792/62778759-a4d0a800-ba87-11e9-8163-689652ef5b16.png)

**Comment by vithefiddler** [comment]
2.2.7Thanks,Vi970-215-6366Sent from my high-functioning smartphone.
-------- Original message --------From: Gonzalo Dominguez <notifications@github.com> Date: 8/9/19  6:25 AM  (GMT-07:00) To: ebizmarts/magento2-mandrill <magento2-mandrill@noreply.github.com> Cc: Vi Wickam <vi@wickam.net>, Mention <mention@noreply.github.com> Subject: Re: [ebizmarts/magento2-mandrill] Mandrill Config Not Showing in Admin Panel (#120) Hi @vithefiddler
what version of magento do you have?
Click on the Freddie icon

Or expand the Mailchimp menu item


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ebizmarts/magento2-mandrill/issues/120?email_source=notifications\u0026email_token=AABOZWFTIDIWM6G7QFHHOXTQDVO4ZA5CNFSM4IKQ7DZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD36QPHA#issuecomment-519899036",
"url": "https://github.com/ebizmarts/magento2-mandrill/issues/120?email_source=notifications\u0026email_token=AABOZWFTIDIWM6G7QFHHOXTQDVO4ZA5CNFSM4IKQ7DZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD36QPHA#issuecomment-519899036",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
