### ISSUE TITLE
Error when sending emails

### ISSUE THREAD

**Issue by tarasyyyk** [ebizmarts/magento2-mandrill#123]
This error ocurrs when sending emails:
```
PHP Fatal error:  Uncaught Error: Call to a member function toString() on string in /home/integration_m2/integration/source/vendor/ebizmarts/magento2-mandrill/Model/Message.php:74
```

1. Go to Product page
2. Click on Add to Cart
3. Go to Chechout
4. Fill all fields
5. Click "Place Order"

**Expected behavior**
Order created and User goes to Success page.

**Desktop (please complete the following information):**
- OS: macOS
- docker
- module 3.3.16

**Comment by gonzaloebiz** [comment]
Hi @tarasyyyk 

what version of magento do you have?

**Comment by tarasyyyk** [comment]
Hi, @gonzaloebiz 
my Magento version is 2.3.2.
I found same issue, and solution to install package `ebizmarts/magento2-mandrillsmtp`, so this issue can be closed.
