### ISSUE TITLE
Extension Not compatible /broken with 2.3.3

### ISSUE THREAD

**Issue by janmyszkier** [ebizmarts/magento2-mandrill#124]
**Describe the bug**
Emails are not being sent at all, code is not compatible with `EmailMessage` class

**To Reproduce**
go to custmer register
register an account
see how emails are not being sent 

**Expected behavior**
emails should be sent with no error

**Screenshots**
no screenshots, 

**Additional context**
composer versions:
```
        "magento/product-community-edition": "2.3.3",
        "ebizmarts/magento2-mandrill": "^3.3",
```
note: readme should also include which version to use with magento 2.3.X which doesn't seem to be the case right now

**Comment by gonzaloebiz** [comment]
Hi @janmyszkier 

use https://github.com/ebizmarts/magento2-mandrill-smtp/releases

Best
