### ISSUE TITLE
M2.3.3 Critical Error - Wrong Invalid argument passed Ebizmarts\Mandrill\Model\Transport constructor

### ISSUE THREAD

**Issue by nghelo** [ebizmarts/magento2-mandrill#125]
Type Error occurred when creating object: Ebizmarts\Mandrill\Model\Transport\Interceptor, Argument 1 passed to Ebizmarts\Mandrill\Model\Transport\Interceptor::__construct() must be an instance of Ebizmarts\Mandrill\Model\Message, instance of Magento\Framework\Mail\EmailMessage given

**Comment by gonzaloebiz** [comment]
Hi @nghelo 

thanks for choosing our extensions.
for magento 2.3.3 please take a look at https://github.com/ebizmarts/magento2-mandrill-smtp/releases

Best
