### ISSUE TITLE
Magento 2.3.3 Incompatibility

### ISSUE THREAD

**Issue by gaurav-s** [ebizmarts/magento2-mandrill#127]
After upgrading to 2.3.3, not able to send the mails with this exception:

main.CRITICAL: Type Error occurred when creating object: Ebizmarts\Mandrill\Model\Transport\Interceptor, Argument 1 passed to Ebizmarts\Mandrill\Model\Transport\Interceptor::__construct() must be an instance of Ebizmarts\Mandrill\Model\Message, instance of Magento\Framework\Mail\EmailMessage given

**Comment by gonzaloebiz** [comment]
Please use https://github.com/ebizmarts/magento2-mandrill-smtp/releases

Best

**Comment by shrma-smit** [comment]
@gonzaloebiz We were using the Ebizmarts Mandrill extension earlier and the variables we've created were successfully passed in the Mandrill. This extension only supports Magento 2.3.2 as you've mentioned above.

We've upgraded the Magento to 2.3.3 on our website and installed the alternative solution Ebizmarts MandrillSmtp (https://github.com/ebizmarts/magento2-mandrill-smtp) for this extension. After installing this extension, we're unable to pass the custom dynamic variables in our emails.

Can you please suggest a way how to do it.
