### ISSUE TITLE
Error when sending Test email for Magento 2.3.3

### ISSUE THREAD

**Issue by Vbak** [ebizmarts/magento2-mandrill#128]
**Describe the bug**
When you try to test the module with the test email through admin panel and error is happening for Magento 2.3.3 and the email doesn't get send.

**To Reproduce**
1. Go to Stores->configuration->Mandrill
2. Enable Module with proper API key.
3. Add test email
4. Click Send email

**Expected behavior**
Expected to send the email.

**What is happening**
An error is happening instead: Type Error occurred when creating object: Ebizmarts\Mandrill\Model\Transport\Interceptor
and fails to send the email

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser chrome
- Magento Version 2.3.3

**Comment by gonzaloebiz** [comment]
Hi @Vbak 

for magento 2.3.3 please use this https://github.com/ebizmarts/magento2-mandrill-smtp/releases

Best
