### ISSUE TITLE
Couldnt send test Emails

### ISSUE THREAD

**Issue by Elamurugan-Nallathambi** [ebizmarts/magento2-mandrill#129]
Configured with sub account API Key in Magento Commerce 2.3.3 after installing mandrill through composer using  `composer require ebizmarts/magento2-mandrill:3.3.15` and when I try send test email I get

`{
  "0": "Type Error occurred when creating object: Ebizmarts\\Mandrill\\Model\\Transport\\Interceptor",
  "1": "<pre>#1 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]\n#2 Magento\\Framework\\ObjectManager\\ObjectManager->create() called at [generated/code/Ebizmarts/Mandrill/Model/TransportFactory.php:43]\n#3 Ebizmarts\\Mandrill\\Model\\TransportFactory->create() called at [vendor/ebizmarts/magento2-mandrill/Model/Plugin/TransportInterfaceFactory.php:60]\n#4 Ebizmarts\\Mandrill\\Model\\Plugin\\TransportInterfaceFactory->aroundCreate() called at [vendor/magento/framework/Interception/Interceptor.php:135]\n#5 Magento\\Framework\\Mail\\TransportInterfaceFactory\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]\n#6 Magento\\Framework\\Mail\\TransportInterfaceFactory\\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/Mail/TransportInterfaceFactory/Interceptor.php:26]\n#7 Magento\\Framework\\Mail\\TransportInterfaceFactory\\Interceptor->create() called at [vendor/magento/framework/Mail/Template/TransportBuilder.php:338]\n#8 Magento\\Framework\\Mail\\Template\\TransportBuilder->getTransport() called at [vendor/ebizmarts/magento2-mandrill/Controller/Adminhtml/Email/Test.php:52]\n#9 Ebizmarts\\Mandrill\\Controller\\Adminhtml\\Email\\Test->execute() called at [vendor/magento/framework/App/Action/Action.php:108]\n#10 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:231]\n#11 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]\n#12 Ebizmarts\\Mandrill\\Controller\\Adminhtml\\Email\\Test\\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]\n#13 Ebizmarts\\Mandrill\\Controller\\Adminhtml\\Email\\Test\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]\n#14 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]\n#15 Ebizmarts\\Mandrill\\Controller\\Adminhtml\\Email\\Test\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]\n#16 Ebizmarts\\Mandrill\\Controller\\Adminhtml\\Email\\Test\\Interceptor->___callPlugins() called at [generated/code/Ebizmarts/Mandrill/Controller/Adminhtml/Email/Test/Interceptor.php:26]\n#17 Ebizmarts\\Mandrill\\Controller\\Adminhtml\\Email\\Test\\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:159]\n#18 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:99]\n#19 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]\n#20 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]\n#21 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]\n#22 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]\n#23 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:137]\n#24 Magento\\Framework\\App\\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]\n#25 Magento\\Framework\\App\\Bootstrap->run() called at [pub/index.php:41]\n</pre>",
  "url": "/backend/mandrilltest/email/test/?isAjax=true",
  "script_name": "/index.php"
}`

Server running in nginx + PHP 7.2 without any Mailing server and I did tried installing `mailchimp/mc-magento2` just to see if that has any dependency and still then also its not working.

**Comment by gonzaloebiz** [comment]
Hi @Elamurugan-Nallathambi 

for magento 2.3 please use this https://github.com/ebizmarts/magento2-mandrill-smtp/releases

Best

**Comment by Elamurugan-Nallathambi** [comment]
@gonzaloebiz Thanks for pointing at right repo. I no longer able to send test email from this extension, do I still need to configure another SMTP extension to make use of Mandrill extension SMTP service? Currently after configuring it when I try send email from admin am not getting any emails.

**Comment by gonzaloebiz** [comment]
You need to uninstall this extension

**Comment by Elamurugan-Nallathambi** [comment]
Removed this extension, added the `ebizmarts/magento2-mandrillsmtp:102.3.3` extension, ran complete clean up, from M2 took care of all setup:up process and this domain is running with in a VPN network. No other mailing lib configured/setup in this server/environment. When I try forgot password request either from admin or from customer end not getting emails.

**Comment by gonzaloebiz** [comment]
Hi @Elamurugan-Nallathambi 

you already take a look at the magento logs and php logs?

**Comment by Elamurugan-Nallathambi** [comment]
No logs found regarding the smtp or mailing. My configuration looks like this

![Screen Shot 2019-12-14 at 2 07 19 PM](https://user-images.githubusercontent.com/54947876/70853374-36f41d00-1e7b-11ea-92c7-edf8293c9584.png)

Mail Sending settings under Stores > Config > Advanced > System
![Screen Shot 2019-12-14 at 2 09 04 PM](https://user-images.githubusercontent.com/54947876/70853385-4a9f8380-1e7b-11ea-874e-39699d6ca467.png)

Even after changing it to below settings then also mail not going out

```
Host: smtp.mandrillapp.com
Port: 587
```

**Comment by Elamurugan-Nallathambi** [comment]
@gonzaloebiz is there any integration document/guide to show how Mailchimp/mandril smtp mailing service can/will work with Magento 2 and where we can see sent mail log? 

From the same account under different sub account we are able to send out emails from Magento 1, with Magento 2 only we are not able to do so. From server all incoming/outgoing ports are open and firewall issue.
