### ISSUE TITLE
Error while run composer with php 7.3.14

### ISSUE THREAD

**Issue by mohdali27** [ebizmarts/magento2-mandrill#130]
I am using the magento 2.3.4 and php 7.3.14 .
When i install the extension using composer(composer require ebizmarts/magento2-mandrill:3.2.17)
I am getting the below error and unable to install this. Please check and fix the issue.

Problem 1
    - magento/module-sales 101.0.10 requires php ~7.0.13||~7.1.0||~7.2.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - magento/module-sales 101.0.9 requires php ~7.0.13|~7.1.0|~7.2.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - magento/module-sales 101.0.8 requires php ~7.0.13|~7.1.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - magento/module-sales 101.0.7 requires php ~7.0.13|~7.1.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - magento/module-sales 101.0.6 requires php ~7.0.13|~7.1.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - magento/module-sales 101.0.5 requires php ~7.0.13|~7.1.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - magento/module-sales 101.0.4 requires php ~7.0.13|~7.1.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - magento/module-sales 101.0.3 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - ebizmarts/magento2-mandrill 3.2.17 requires magento/module-sales ^101.0.3 -> satisfiable by magento/module-sales[101.0.3, 101.0.4, 101.0.5, 101.0.6, 101.0.7, 101.0.8, 101.0.9, 101.0.10].
    - Installation request for ebizmarts/magento2-mandrill 3.2.17 -> satisfiable by ebizmarts/magento2-mandrill[3.2.17]

**Comment by gonzaloebiz** [comment]
This version is not compatible with magento 2.3.4, please use https://github.com/ebizmarts/magento2-mandrill-smtp

Best
