### ISSUE TITLE
Wrong structure for replay to header

### ISSUE THREAD

**Issue by kilis** [ebizmarts/magento2-mandrill#14]
Hi,
I have found a bug while creating Replay To header for my app.
When i send email this structure is created.
`{
    "message": {
        "subject": "Product Questions",
        "from_name": "Smth",
        "from_email": "no-replay@Smth.com",
        "to": [
            {
                "email": "kristapss@Smth.com"
            }
        ],
        "headers": [
            {
                "Reply-To": " <kristapsst@Smth.com>"
            }
        ],
        "text": "Name: Kristaps \n\n        Message: test email"
    },
    "async": false,
    "ip_pool": null,
    "send_at": null,
    "key": "apikey"
}`
And Replay to header doesn't appear in email. When i remove Brackets  manualy in Mandrill APi sandbox it is working. And Reply to is appearing in email 
`{
    "message": {
        "subject": "Product Questions",
        "from_name": "Smth",
        "from_email": "no-replay@Smth.com",
        "to": [
            {
                "email": "kristapsst@Smth.com"
            }
        ],
        "headers": {
            "Reply-To": "kristapsst@Smth.com"
        },
        "text": "Name: Kristaps \n\n        Message: zdxfghg"
    },
    "async": false,
    "ip_pool": null,
    "send_at": null,
    "key": "apikey"
}`
I think the bug relies in here https://github.com/ebizmarts/magento2-mandrill/blob/develop/Model/Message.php#L192

**Comment by centerax** [comment]
@kilis I think this issue is still opened by mistake.

Can you confirm you are still facing this problem?

**Comment by centerax** [comment]
closing, no reply.
