### ISSUE TITLE
Customer registration bug - Customer could not saved

### ISSUE THREAD

**Issue by peccopi** [ebizmarts/magento2-mandrill#15]
After create customer Account the message "Customer could not saved" returned.
But the Customer is successfully created and can find in backend.
Mage Monkey Module 3.0.6 is configured other modules actually not.

> [2016-09-05 09:49:57] main.CRITICAL: Exception message: Notice: Trying to get property of non-object in /home/vnmoebel/domains/vnmoebel.de/app/code/Ebizmarts/Mandrill/Model/Transport.php on line 84
> Trace: #0 /home/vnmoebel/domains/vnmoebel.de/app/code/Ebizmarts/Mandrill/Model/Transport.php(84): Magento\Framework\App\ErrorHandler->handler(8, 'Trying to get p...', '/home/vnmoebel/...', 84, Array)
> # 1 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Interceptor.php(146): Ebizmarts\Mandrill\Model\Transport->sendMessage()
> # 2 /home/vnmoebel/domains/vnmoebel.de/var/generation/Ebizmarts/Mandrill/Model/Transport/Interceptor.php(26): Ebizmarts\Mandrill\Model\Transport\Interceptor->___callPlugins('sendMessage', Array, Array)
> # 3 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-customer/Model/EmailNotification.php(239): Ebizmarts\Mandrill\Model\Transport\Interceptor->sendMessage()
> # 4 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-customer/Model/EmailNotification.php(363): Magento\Customer\Model\EmailNotification->sendEmailTemplate(Object(Magento\Customer\Model\Data\Customer), 'customer/create...', 'customer/create...', Array, 1)
> # 5 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-customer/Model/AccountManagement.php(777): Magento\Customer\Model\EmailNotification->newAccount(Object(Magento\Customer\Model\Data\Customer), 'registered', 'http://demo.vnm...', 1)
> # 6 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-customer/Model/AccountManagement.php(737): Magento\Customer\Model\AccountManagement->sendEmailConfirmation(Object(Magento\Customer\Model\Data\Customer), 'http://demo.vnm...')
> # 7 /home/vnmoebel/domains/vnmoebel.de/var/generation/Magento/Customer/Model/AccountManagement/Interceptor.php(141): Magento\Customer\Model\AccountManagement->createAccountWithPasswordHash(Object(Magento\Customer\Model\Data\Customer), '19ff2c910c8b303...', 'http://demo.vnm...')
> # 8 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-customer/Model/AccountManagement.php(662): Magento\Customer\Model\AccountManagement\Interceptor->createAccountWithPasswordHash(Object(Magento\Customer\Model\Data\Customer), '19ff2c910c8b303...', 'http://demo.vnm...')
> # 9 /home/vnmoebel/domains/vnmoebel.de/var/generation/Magento/Customer/Model/AccountManagement/Interceptor.php(128): Magento\Customer\Model\AccountManagement->createAccount(Object(Magento\Customer\Model\Data\Customer), 'Test123!', 'http://demo.vnm...')
> # 10 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-customer/Controller/Account/CreatePost.php(277): Magento\Customer\Model\AccountManagement\Interceptor->createAccount(Object(Magento\Customer\Model\Data\Customer), 'Test123!', 'http://demo.vnm...')
> # 11 /home/vnmoebel/domains/vnmoebel.de/var/generation/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(24): Magento\Customer\Controller\Account\CreatePost->execute()
> # 12 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/App/Action/Action.php(102): Magento\Customer\Controller\Account\CreatePost\Interceptor->execute()
> # 13 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
> # 14 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent('dispatch', Array)
> # 15 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'storeCheck')
> # 16 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
> # 17 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> # 18 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'contextPlugin')
> # 19 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
> # 20 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> # 21 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'customer-app-ac...')
> # 22 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
> # 23 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> # 24 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'weee-app-action...')
> # 25 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
> # 26 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> # 27 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'tax-app-action-...')
> # 28 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
> # 29 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> # 30 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'customer_accoun...')
> # 31 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-customer/Controller/Plugin/Account.php(60): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
> # 32 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Customer\Controller\Plugin\Account->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> # 33 /home/vnmoebel/domains/vnmoebel.de/var/generation/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(39): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins('dispatch', Array, Array)
> # 34 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/App/FrontController.php(55): Magento\Customer\Controller\Account\CreatePost\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> # 35 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
> # 36 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
> # 37 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
> # 38 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
> # 39 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> # 40 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
> # 41 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
> # 42 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> # 43 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
> # 44 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
> # 45 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> # 46 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
> # 47 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
> # 48 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> # 49 /home/vnmoebel/domains/vnmoebel.de/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
> # 50 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> # 51 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
> # 52 /home/vnmoebel/domains/vnmoebel.de/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
> # 53 {main}

**Comment by SantiParagarino** [comment]
Hello @peccopi ,

Oh so the problem is when Mandrill is not enabled. You should be able to get that working properly running the command **magento module:disable Ebizmarts_AutoResponder Ebizmarts_AbandonedCart Ebizmarts_Mandrill**

If this doesn't solve your problem we can re-open this issue.

Regards.

**Comment by peccopi** [comment]
Hi,
do disable the other modules solve thre problem.
Thank you !

**Comment by SantiParagarino** [comment]
Great to hear that!

You are welcome!
