### ISSUE TITLE
Customer creation email trigger even if module is disabled?

### ISSUE THREAD

**Issue by pushonscott** [ebizmarts/magento2-mandrill#19]
Installed the module and set to disabled (as we are not ready for production yet.). However, when i try to create a new customer, i receive the notice:

`Notice: Trying to get property of non-object in vendor/ebizmarts/magento2-mandrill/Model/Transport.php on line 84`

Which is causing a magento exception to be thrown:

`Something went wrong while saving the customer.`

Should mandril try to be used even though the extension is disabled from the admin?

**Comment by pushonscott** [comment]
Any updates on this @gonzaloebiz?

**Comment by rajesh0608** [comment]
use command prompt to disable module. In my case working fine.
