### ISSUE TITLE
Invalid block type: Ebizmarts\MageMonkey\Block\Adminhtml\System\Config\Fieldset\Hint

### ISSUE THREAD

**Issue by comunidademagento** [ebizmarts/magento2-mandrill#2]
Generate this error when access ...

Menu > System > Magemonkey > Magemonkey

Invalid block type: Ebizmarts\MageMonkey\Block\Adminhtml\System\Config\Fieldset\Hint
#0 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout/Generator/Block.php(237): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('Ebizmarts\MageM...', Array)
#1 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(762): Magento\Framework\View\Layout\Generator\Block->createBlock('Ebizmarts\MageM...', 'adminhtml\syste...', Array)
#2 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(745): Magento\Framework\View\Layout->_createBlock('Ebizmarts\MageM...', 'adminhtml\syste...', Array)
#3 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(349): Magento\Framework\View\Layout->createBlock('Ebizmarts\MageM...', '', Array)
#4 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(975): Magento\Framework\View\Layout\Interceptor->createBlock('Ebizmarts\MageM...')
#5 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(518): Magento\Framework\View\Layout->getBlockSingleton('Ebizmarts\MageM...')
#6 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Config/Block/System/Config/Form.php(194): Magento\Framework\View\Layout\Interceptor->getBlockSingleton('Ebizmarts\MageM...')
#7 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Config/Block/System/Config/Form.php(170): Magento\Config\Block\System\Config\Form->_initGroup(Object(Magento\Config\Model\Config\Structure\Element\Group), Object(Magento\Config\Model\Config\Structure\Element\Section), Object(Magento\Framework\Data\Form))
#8 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Config/Block/System/Config/Form.php(458): Magento\Config\Block\System\Config\Form->initForm()
#9 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(651): Magento\Config\Block\System\Config\Form->_beforeToHtml()
#10 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(544): Magento\Framework\View\Element\AbstractBlock->toHtml()
#11 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderBlock('system\config\f...')
#12 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system\config\f...')
#13 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(474): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system\config\f...')
#14 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system\config\f...', true)
#15 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(492): Magento\Framework\View\Layout\Interceptor->renderElement('system\config\f...', true)
#16 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Config/view/adminhtml/templates/system/config/edit.phtml(22): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#17 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/home/magento2u...')
#18 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/home/magento2u...', Array)
#19 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Element/Template.php(275): Magento\Framework\View\Element\Template->fetchView('/home/magento2u...')
#20 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#21 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(652): Magento\Backend\Block\Template->_toHtml()
#22 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(544): Magento\Framework\View\Element\AbstractBlock->toHtml()
#23 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
#24 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
#25 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(474): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system.config.e...')
#26 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system.config.e...', true)
#27 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(571): Magento\Framework\View\Layout\Interceptor->renderElement('system.config.e...')
#28 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(522): Magento\Framework\View\Layout->_renderContainer('content')
#29 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#30 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(474): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#31 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#32 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(571): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#33 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(522): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#34 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#35 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(474): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#36 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#37 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(571): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#38 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(522): Magento\Framework\View\Layout->_renderContainer('main.col')
#39 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#40 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(474): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#41 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#42 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(571): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#43 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(522): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#44 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#45 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(474): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#46 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#47 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(571): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#48 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(522): Magento\Framework\View\Layout->_renderContainer('page.content')
#49 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#50 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(474): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#51 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#52 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(571): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#53 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(522): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#54 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#55 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(474): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#56 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#57 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(571): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#58 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(522): Magento\Framework\View\Layout->_renderContainer('backend.page')
#59 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#60 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(474): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#61 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#62 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(571): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#63 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(522): Magento\Framework\View\Layout->_renderContainer('root')
#64 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#65 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(474): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#66 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#67 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(940): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#68 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#69 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Result/Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#70 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#71 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#72 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/App/Http.php(119): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#73 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#74 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#75 {main}

![captura de tela de 2015-09-17 22 52 12](https://cloud.githubusercontent.com/assets/7476455/9950227/c45af1a8-5d8e-11e5-86e7-48a90a95def9.png)

**Comment by gonzaloebiz** [comment]
Check if you have this file https://github.com/ebizmarts/magento2-magemonkey/blob/master/Block/Adminhtml/System/Config/Fieldset/Hint.php in your installation.
If not, please reinstall the extension or download the file from github

Best
