### ISSUE TITLE
Mail cant be sent

### ISSUE THREAD

**Issue by dcarnelutti** [ebizmarts/magento2-mandrill#20]
Im trying to send emails from my magento2. Im getting this message.

Im using Magento 2.1.3
Mandrill is configured, Mailchimp is also properly configured

Any ideas?

`[2017-02-08 15:38:04] main.CRITICAL: Exception message: The message should be an instance of \Zend_Mail
Trace: #0 /var/www/html/mg/vendor/bogardo/mailgun-magento2/Mail/Transport.php(39): Magento\Framework\Mail\Transport->__construct(Object(Ebizmarts\Mandrill\Model\Message), NULL)
#1 /var/www/html/mg/var/generation/Bogardo/Mailgun/Mail/Transport/Interceptor.php(14): Bogardo\Mailgun\Mail\Transport->__construct(Object(Ebizmarts\Mandrill\Model\Message), NULL)
#2 /var/www/html/mg/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Bogardo\Mailgun\Mail\Transport\Interceptor->__construct(Object(Ebizmarts\Mandrill\Model\Message), NULL)
#3 /var/www/html/mg/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Bogardo\\Mailgun...', Array)
#4 /var/www/html/mg/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Bogardo\\Mailgun...', Array)
#5 /var/www/html/mg/vendor/magento/framework/Mail/TransportInterfaceFactory.php(50): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#6 /var/www/html/mg/vendor/magento/framework/Mail/Template/TransportBuilder.php(228): Magento\Framework\Mail\TransportInterfaceFactory->create(Array)
#7 /var/www/html/mg/vendor/magento/module-customer/Model/EmailNotification.php(237): Magento\Framework\Mail\Template\TransportBuilder->getTransport()
#8 /var/www/html/mg/vendor/magento/module-customer/Model/EmailNotification.php(320): Magento\Customer\Model\EmailNotification->sendEmailTemplate(Object(Magento\Customer\Model\Data\Customer), 'customer/passwo...', 'customer/passwo...', Array, '1')
#9 /var/www/html/mg/vendor/magento/module-customer/Model/AccountManagement.php(514): Magento\Customer\Model\EmailNotification->passwordResetConfirmation(Object(Magento\Customer\Model\Data\Customer))
#10 /var/www/html/mg/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Customer\Model\AccountManagement->initiatePasswordReset('dariocarnelutti...', 'email_reset', '1')
#11 /var/www/html/mg/var/generation/Magento/Customer/Model/AccountManagement/Interceptor.php(91): Magento\Customer\Model\AccountManagement\Interceptor->___callPlugins('initiatePasswor...', Array, Array)
#12 /var/www/html/mg/vendor/magento/module-customer/Controller/Account/ForgotPasswordPost.php(72): Magento\Customer\Model\AccountManagement\Interceptor->initiatePasswordReset('dariocarnelutti...', 'email_reset')
#13 /var/www/html/mg/var/generation/Magento/Customer/Controller/Account/ForgotPasswordPost/Interceptor.php(24): Magento\Customer\Controller\Account\ForgotPasswordPost->execute()
#14 /var/www/html/mg/vendor/magento/framework/App/Action/Action.php(102): Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor->execute()
#15 /var/www/html/mg/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#16 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor->___callParent('dispatch', Array)
#17 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor), Array, 'contextPlugin')
#18 /var/www/html/mg/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#19 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#20 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor), Array, 'customer-app-ac...')
#21 /var/www/html/mg/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#22 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor), Array, 'storeCheck')
#24 /var/www/html/mg/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor), Array, 'customer_accoun...')
#27 /var/www/html/mg/vendor/magento/module-customer/Controller/Plugin/Account.php(60): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Controller\Plugin\Account->aroundDispatch(Object(Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor), Array, 'weee-app-action...')
#30 /var/www/html/mg/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /var/www/html/mg/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor), Array, 'tax-app-action-...')
#33 /var/www/html/mg/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /var/www/html/mg/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /var/www/html/mg/var/generation/Magento/Customer/Controller/Account/ForgotPasswordPost/Interceptor.php(39): Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /var/www/html/mg/vendor/magento/framework/App/FrontController.php(55): Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /var/www/html/mg/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#38 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#39 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#40 /var/www/html/mg/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#41 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#42 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#43 /var/www/html/mg/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#44 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#45 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#46 /var/www/html/mg/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#47 /var/www/html/mg/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#48 /var/www/html/mg/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#49 /var/www/html/mg/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#50 /var/www/html/mg/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#51 /var/www/html/mg/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#52 /var/www/html/mg/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#53 /var/www/html/mg/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#54 /var/www/html/mg/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#55 {main} [] []
`

**Comment by gonzaloebiz** [comment]
Hi @dcarnelutti 

thanks for your contact.
I think you have a conflict with mailgun extension

Best
