### ISSUE TITLE
Log setting not used Mandrill not sending mail

### ISSUE THREAD

**Issue by clivewalkden** [ebizmarts/magento2-mandrill#21]
Hi,

You have a log setting in the admin but I'm not seeing any logs being generated when I turn it on. Looking through the source code I can't see it actually being called in anywhere.

As my installation isn't sending any mail through Mandrill a log of what is happening would be helpful.

Kind regards,

Clive

**Comment by SantiParagarino** [comment]
Hello,

You should see errors showin up in the Magento log files anyways. Please make sure you have the latest version installed via composer. This is the best way to make sure everything has been set up properly.

Please check [this guidelines](https://github.com/ebizmarts/magento2-magemonkey/wiki/Issue-reporting-guidelines) before creating new issues.

Regards.
