### ISSUE TITLE
Exception occurred during setting up Mandrill API key

### ISSUE THREAD

**Issue by sinisa86** [ebizmarts/magento2-mandrill#22]
### Situation - How did you get there?
Stores -> Configuration -> Mandrill. I've set up MageMonkey API key and it was good after save.
Later, I've set up Mandrill API key, and after save it has thrown an Exception.

### Problem - What went wrong?
I got exception after click on Save during Mandrill API key set up.
(Exception stack trace is at the end)

### Possible solution - How should it be?
Looks like Ebizmarts\Mandrill\Model\Api\Mandrill constructor is trying to instantiate itself.

`( ! ) Fatal error: Uncaught Error: Class 'Mandrill' not found in /vagrant/www/app/code/Ebizmarts/Mandrill/Model/Api/Mandrill.php on line 31
( ! ) Error: Class 'Mandrill' not found in /vagrant/www/app/code/Ebizmarts/Mandrill/Model/Api/Mandrill.php on line 31
Call Stack
#	Time	Memory	Function	Location
1	0.0000	363064	{main}( )	.../index.php:0
2	0.0480	3472184	Magento\Framework\App\Bootstrap->run( )	.../index.php:37
3	0.0488	3504080	Magento\Framework\App\Http->launch( )	.../Bootstrap.php:258
4	0.1035	8233152	Magento\Framework\App\FrontController\Interceptor->dispatch( )	.../Http.php:135
5	0.1054	8201688	Magento\Framework\App\FrontController\Interceptor->___callPlugins( )	.../Interceptor.php:26
6	0.1194	9099208	Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch( )	.../Interceptor.php:142
7	0.1205	9099240	Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}( )	.../DbStatusValidator.php:69
8	0.1205	9099616	Magento\Framework\Interception\Chain\Chain->invokeNext( )	.../Interceptor.php:138
9	0.1205	9099656	Magento\Framework\App\FrontController\Interceptor->___callParent( )	.../Chain.php:70
10	0.1205	9099656	Magento\Framework\App\FrontController->dispatch( )	.../Interceptor.php:74
11	0.1330	9772168	Magento\Framework\App\Router\Base->match( )	.../FrontController.php:50
12	0.1330	9773256	Magento\Framework\App\Router\Base->matchAction( )	.../Base.php:161
13	0.1367	9919416	Magento\Framework\App\ActionFactory->create( )	.../Base.php:300
14	0.1367	9919416	Magento\Framework\ObjectManager\ObjectManager->create( )	.../ActionFactory.php:40
15	0.1367	9919416	Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create( )	.../ObjectManager.php:57
16	0.1402	10067400	Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments( )	.../Developer.php:82
17	0.1402	10068080	Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument( )	.../Developer.php:53
18	0.1402	10068080	Magento\Framework\ObjectManager\ObjectManager->get( )	.../AbstractFactory.php:126
19	0.1402	10068080	Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create( )	.../ObjectManager.php:71
20	0.1421	10160048	Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments( )	.../Developer.php:82
21	0.1422	10160936	Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument( )	.../Developer.php:53
22	0.1422	10160936	Magento\Framework\ObjectManager\ObjectManager->get( )	.../AbstractFactory.php:126
23	0.1422	10160936	Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create( )	.../ObjectManager.php:71
24	0.1423	10166128	Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments( )	.../Developer.php:82
25	0.1424	10167824	Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument( )	.../Developer.php:53
26	0.1424	10167824	Magento\Framework\ObjectManager\ObjectManager->get( )	.../AbstractFactory.php:126
27	0.1424	10167824	Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create( )	.../ObjectManager.php:71
28	0.1491	10489936	Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject( )	.../Developer.php:89
29	0.1491	10490256	Magento\Backend\Model\Session\Interceptor->__construct( )	.../AbstractFactory.php:93
30	0.1492	10490256	Magento\Framework\Session\SessionManager->__construct( )	.../Interceptor.php:14
31	0.1492	10490256	Magento\Backend\Model\Session\Interceptor->start( )	.../SessionManager.php:130
32	0.1492	10490256	Magento\Framework\Session\SessionManager->start( )	.../Interceptor.php:63
33	0.1493	10496240	session_start ( )	.../SessionManager.php:189
34	0.1551	11101976	Magento\User\Model\User->__wakeup( )	.../SessionManager.php:189
35	0.1564	11127776	Magento\Framework\ObjectManager\ObjectManager->get( )	.../User.php:204
36	0.1564	11127776	Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create( )	.../ObjectManager.php:71
37	0.1567	11133800	Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments( )	.../Developer.php:82
38	0.1569	11136632	Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument( )	.../Developer.php:53
39	0.1569	11136632	Magento\Framework\ObjectManager\ObjectManager->get( )	.../AbstractFactory.php:126
40	0.1569	11136632	Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create( )	.../ObjectManager.php:71
41	0.1580	11184800	Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments( )	.../Developer.php:82
42	0.1581	11186784	Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument( )	.../Developer.php:53
43	0.1581	11186784	Magento\Framework\ObjectManager\ObjectManager->get( )	.../AbstractFactory.php:126
44	0.1581	11186784	Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create( )	.../ObjectManager.php:71
45	0.1581	11188112	Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject( )	.../Developer.php:89
46	0.1581	11188168	Ebizmarts\Mandrill\Model\Api\Mandrill->__construct( )	.../AbstractFactory.php:93
`

**Comment by SantiParagarino** [comment]
Hello @sinisa86 
That error is telling you that the Mandrill library is not being found in your Magento installation.
This is why we always recommend to install Magento 2 extensions via composer.
With composer you can get the missing library with the command **composer require mandrill/mandrill**

Regards,
