### ISSUE TITLE
Attachments not working when sending through Mandrill

### ISSUE THREAD

**Issue by vishalaureate** [ebizmarts/magento2-mandrill#25]
We are having problems when sending attachments from Magento 2 through Mandrill. We have tested both PDF and ZIP files.

**Comment by SantiParagarino** [comment]
Hello @gelanivishal 

Thanks for your feedback.
Please read this [guidelines](https://github.com/ebizmarts/magento2-magemonkey/wiki/Issue-reporting-guidelines) before creating an issue.

Regards.
