### ISSUE TITLE
Fatal error: Class 'Mandrill' not found in /home/myshulca/public_html/app/code/Ebizmarts/Mandrill/Model/Api/Mandrill.php on line 31

### ISSUE THREAD

**Issue by manojind** [ebizmarts/magento2-mandrill#29]
Fatal error: Class 'Mandrill' not found in /home/myshulca/public_html/app/code/Ebizmarts/Mandrill/Model/Api/Mandrill.php on line 31

**Comment by ebizmarts-keller** [comment]
You have to install the Mandrill library via composer to get rid of this error.

https://packagist.org/packages/mandrill/mandrill
