### ISSUE TITLE
unable to send email

### ISSUE THREAD

**Issue by etessari** [ebizmarts/magento2-mandrill#30]
Actually disabling general activation settings doesn't seems to work.
I have disabled mandrill by setting "mandrill/general/active" => "No", but magento keep instantiate Ebizmarts\Mandrill\Model\Transport for email sending.
Debugging I have seen that the method Ebizmarts\Mandrill\Helper\Data::isActive()
isn't called anywhere.
Thanks

**Comment by centerax** [comment]
working on it @etessari 

we will provide a fix shortly.

**Comment by centerax** [comment]
@etessari , can you please test whats on **develop** and let me know how it goes?

**Comment by MaxyBlack** [comment]
Hello, is there any progress on this issue? I have a similar problem and I don't know if I should make my own module to fix this or wait for new version.

**Comment by centerax** [comment]
@MaxyBlack  How you tested the code that sits on develop?

**Comment by MaxyBlack** [comment]
@centerax I've made a quick test on my test env and it is working but the question is how long it will take before it will be officially released?

**Comment by centerax** [comment]
Will release it today
	_____________________________

**Comment by centerax** [comment]
We will make a new release today.

**Comment by centerax** [comment]
version 3.0.11 released
Github updated https://github.com/ebizmarts/magento2-mandrill/releases/tag/3.0.11 and packagist updated: https://packagist.org/packages/ebizmarts/magento2-mandrill#3.0.11

**Comment by Silarn** [comment]
So did anybody actually bother to test sending an email after this 'fix'?

The problem is it instantiates the Transport model but doesn't pass it any data. This means nothing ever gets sent via Mandrill.

**Comment by bharatgunani** [comment]
I am using latest version , but i still have same issue.
