### ISSUE TITLE
Magento Emails are not sending

### ISSUE THREAD

**Issue by coatesjonathan** [ebizmarts/magento2-mandrill#44]
Hi, 

The default Magento 2 emails are no longer sending?

Can you suggest a quick fix please?

**Comment by centerax** [comment]
have you tried the latest version?

do you get any error message?

**Comment by lumijino** [comment]
Hi @centerax ,

Same error here, default magento emails are not sending. even if after upgrade to 3.0.12

**Comment by centerax** [comment]
that is strange. any errors?

**Comment by lumijino** [comment]
No errors in Magento/ server logs

**Comment by lumijino** [comment]
Hi @centerax ,

We are receiving the following result on debug on line no. 78 on app/code/Ebizmarts/Mandrill/Model/Transport.php

`$result = {array} [1]
 0 = {array} [4]
  email = "jino@luminescent.digital"
  status = "sent"
  _id = "ee6a435483bb4d9897f771f74b8c73e7"
  reject_reason = null`

**Comment by centerax** [comment]
it is sent as per the logs.

please check the Mandrill API logs.

**Comment by lumijino** [comment]
Hi @centerax ,

yeah, the emails are reaching mandrill and getting delivered. Sorry for the confusions.

But do you know, why its not reaching our inbox even if the status there is Delivered? We are working on test mode.

Thanks
Jino

**Comment by centerax** [comment]
no idea, I recommend you contact Mandrill support.
