### ISSUE TITLE
Call to undefined method Ebizmarts\Mandrill\Model\Transport\Interceptor::send()

### ISSUE THREAD

**Issue by tomelevated** [ebizmarts/magento2-mandrill#46]
I am getting an apache error when I try to execute a command to send in magento 2. Anyone else having this issue.

**Comment by tomelevated** [comment]
[14-Sep-2017 00:18:42 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Ebizmarts\Mandrill\Model\Transport\Interceptor::send() in /home/drbronner/production/magento_2017/vendor/magento/zendframework1/library/Zend/Mail.php:1194
Stack trace:
#0 /home/drbronner/production/magento_2017/vendor/xtento/orderexport/Model/Export.php(977): Zend_Mail->send(Object(Ebizmarts\Mandrill\Model\Transport\Interceptor))
#1 /home/drbronner/production/magento_2017/vendor/xtento/orderexport/Model/Export.php(952): Xtento\OrderExport\Model\Export->errorEmailNotification()
#2 /home/drbronner/production/magento_2017/vendor/xtento/orderexport/Model/Export.php(607): Xtento\OrderExport\Model\Export->saveLog()
#3 /home/drbronner/production/magento_2017/vendor/xtento/orderexport/Model/Export.php(470): Xtento\OrderExport\Model\Export->afterExport()
#4 /home/drbronner/production/magento_2017/vendor/xtento/orderexport/Model/Export.php(278): Xtento\OrderExport\Model\Export->runExport(Array)
#5 /home/drbronner/production/magento_2017/vendor/xtento/orderexport/Controller/Admin in /home/drbronner/production/magento_2017/vendor/magento/zendframework1/library/Zend/Mail.php on line 1194

**Comment by centerax** [comment]
can you specify a bit more detail? maybe [this guide](https://github.com/ebizmarts/magento2-mandrill/blob/develop/CONTRIBUTING.md) on how to create an issue helps.
thanks.
