### ISSUE TITLE
Problem when sending a test mail!

### ISSUE THREAD

**Issue by Andrease89** [ebizmarts/magento2-mandrill#56]
Im getting the following messange when I try to send a test mail throug mandrill:
"A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

Where can I find log files for thos errors? Im using magento 2.2 and recently updated your extension to the latest version. It didn't work before the update eighter though!

Best Regards

**Comment by OxCom** [comment]
@Andrease89 some information can be found in:
``` var/log``` and ```var/report```
Also, please, check your api key and try to get error message from mandrill after call to API

**Comment by SantiParagarino** [comment]
Thanks @OxCom 

@Andrease89 Also please make sure to check your Mandrill account at [mandrillapp.com](mandrillapp.com) in the outbound section of the menu.
Accounts need to be verified and if you see a failure there then it means the email is getting successfully to your account but failing afterwards.

Regards.
