### ISSUE TITLE
Undefined index in PluginList.php

### ISSUE THREAD

**Issue by olgaimproove** [ebizmarts/magento2-mandrill#59]
I upgraded the module to the latest(3.0.13). During `setup:di:compile` Magento gives an exception:
`[Exception]                                                                                                        
  Notice: Undefined index: instance in vendor/magento/framework/Interception/PluginList/Plugi  
  nList.php on line 196 `
Magento version: 2.1.10
It seems like the issue is in ebizmarts/magento2-mandrill/etc/di.xml in a plugin for `Magento\Framework\Mail\TransportInterfaceFactory`

**Comment by centerax** [comment]
could not replicate.

are you certain this relates to our module?

**Comment by shiftenterdev** [comment]
@olgaimproove have you solve this issue? If yes how? plz help me I am also stuck on same issue.
