### ISSUE TITLE
Compatibility with Magento 2.2

### ISSUE THREAD

**Issue by MelissaEbizmarts** [ebizmarts/magento2-mandrill#60]
The module is not compatible with Magento 2.2 yet.

**Comment by jschreck** [comment]
Hello Melissa -

Any idea when we can expect compatibility?

Juergen

**Comment by OxCom** [comment]
@MelissaEbizmarts checked few minute ago with fresh install of magento 2.2. All fine.
Plese, prowide anything that can help us to detect and fix issue.

**Comment by jschreck** [comment]
@MelissaEbizmarts, @OxCom - Yes install works fine. But when I add the API Key and save the config, the admin goes blank. No outputs in system.log, exception.log or php-fpm.logs. I can still navigate to other parts of the admin, but no longer to the Mandrill config until I remove the config entry from the database.

**Comment by SantiParagarino** [comment]
Hello @jschreck @OxCom @jschreck 

The extension is currently working fine with Magento 2.2
For any issues please contact our support at mailchimp@ebizmarts-desk.zendesk.com

Regards.
