### ISSUE TITLE
Mails not being sent at all (not even the Test Email)

### ISSUE THREAD

**Issue by balwant20** [ebizmarts/magento2-mandrill#61]
when i enbale mandrill module then no emails are shoot to customer or admin.i am using mandrill varsion-3.0.13 &magento avrsion-2.1.7

**Comment by OxCom** [comment]
@balwant20 please provide logs/error reports from plugin. I'm using latest version on 2.1.15 and 2.2.2. Be sure that you are using mandrill API key, not mailchimp.

**Comment by centerax** [comment]
@balwant20 Have you tried what @OxCom has mentioned? Did it work?

**Comment by balwant20** [comment]
ya @centerax ,now its work fine....
thanks @OxCom @centerax
