### ISSUE TITLE
Class Templatemap unused?

### ISSUE THREAD

**Issue by SchumacherFM** [ebizmarts/magento2-mandrill#63]
Hi there,

I'm wondering how to map the Mailchimp/Mandrill templates to the Magento templates?

I've discovered class `\Ebizmarts\Mandrill\Block\Adminhtml\System\Config\Form\Field\Templatemap` but it seems that this class is unused.

How do the future feature look like? Can I help? What are the next steps?

Best, Cyrill

**Comment by centerax** [comment]
Hi @SchumacherFM 

This was an attempt to making it work but its a limitation on the Mandrill platform that does not allow this to continue.

We shall delete this file shortly.

**Comment by SchumacherFM** [comment]
Hi @centerax 

can you please describe in some words what the limitation is?

**Comment by centerax** [comment]
the limitation afaik, is that mandrill does not support this. it was on the roadmap and then removed.
