### ISSUE TITLE
Sender email not populated in Order emails for Magento 2.2.4

### ISSUE THREAD

**Issue by Silarn** [ebizmarts/magento2-mandrill#65]
I'm still investigating the issue, but after upgrading our staging server our order emails seem to be failing due to no sender info getting set in the API call.

The test email does work, so the problem must be when it tries to pull the emails for the order.

**Comment by Silarn** [comment]
This is caused by an addition the \Magento\Sales\Model\Order\Email\SenderBuilder which now uses two classes, the old TransportBuilder and a new TransportBuilderByStore, to set the data on the Message model. I'm not entirely sure why this works with the standard Zend_Mail class, but for this module it was causing two entirely separate instances of the Message class to be created. Since the main TransportBuilder manages creating the transport and dispatching the message, the data set by the TransportBuilderByStore was lost.

My current solution is to override the SenderBuilder class and instantiate the two TransportBuilders and the Message manually, passing the single Message instance to both models. This allows the data set by the TransportBuilderByStore to apply to the same message as the TransportBuilder and fixes the issue.

**Comment by Silarn** [comment]
I'm working on a local fix and then I'll create a PR for this repo.

**Comment by klein0r** [comment]
Having the same issue. Have you fixed it @Silarn ?

**Comment by Silarn** [comment]
See the associated PR
