### ISSUE TITLE
Uncaught Error: Class 'Mandrill' not found

### ISSUE THREAD

**Issue by Flipmediaco** [ebizmarts/magento2-mandrill#67]
I suspect this issue relates to the fact that we had the older version of the Mandrill extension that was bundled with MailChimp. Since Upgrading MailChimp extension Mandrill support was removed so installed this repro.

I have removed all data and configuration relating to Mandrill and the extension is installed manually and works up until an API key is saved, then the following error is returned:-

Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Mandrill' not found in /app/code/Ebizmarts/Mandrill/Model/Api/Mandrill.php:31\nStack trace:\n#0 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Ebizmarts\\Mandrill\\Model\\Api\\Mandrill->__construct(Object(Ebizmarts\\Mandrill\\Helper\\Data))\n#1 /vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Ebizmarts\\\\Mandr...', Array)\n#2 /vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Ebizmarts\\\\Mandr...')\n#3 /vendor/magento/framework/ObjectManager/Factory/Compil...\n', referer: https://domain/backend/adminhtml/system_config/index/key/6c0fd5016c1e82f2f8b45b7beb135eb86c06e5014658272c87140bf80751378b/

**Comment by Silarn** [comment]
How did you install the module? If you use composer, the mandrill packages are required and should be automatically available.

Otherwise, you will have to include the Mandrill API packages manually as well.

**Comment by gonzaloebiz** [comment]
this is not an issue, you must install mandrill/mandrill package, run
composer require mandrill/mandrill

Best

**Comment by Flipmediaco** [comment]
Thanks for your guidance, I had installed manually so the dependancy was missed and installing the mandrill/mandrill package resolved the problem. Thanks again
