### ISSUE TITLE
Email sending failed: invalid-sender

### ISSUE THREAD

**Issue by Flipmediaco** [ebizmarts/magento2-mandrill#75]
**Describe the bug**
Order, Shipping Emails not sent. Attempting to email a comment on an order results in a alert pop up stating "Email sending failed: invalid-sender". Forgot password, Contact Form and Mandrill test emails are sent. I suspect there is an issue with the "Form" aspect of the sales and shipping emails when Mandrill is called to send. In all email cases above the from / sender email address is the same. 

**To Reproduce**
1. Place Order via Magento Checkout
2. No sales / order confirmation email delivered
3. Login to admin area and locate order placed
4. Submit order comment ticking box "Notify Customer by Email"
5. Alert box states "Email sending failed: invalid-sender"

**Expected behavior**
Sales, Order Confirmation emails sent / delivered.

**Additional context**
Prior to upgrading to Magento ver. 2.2.4 and Ebizmarts_Mandrill 3.0.13 this was not an issue. No changes were made to configuration.

**Comment by jaredchu** [comment]
I'm facing the same issue.
Magento 2.2.4
Ebizmarts_Mandrill 3.1.0

**Comment by Flipmediaco** [comment]
Hi jaredchu

This issue is not related to this Extension. You will have updated to Magento 2.2.4, this comes packaged with 3 Amazon Extensions supporting Amazon Pay. Assuming you do not require Amazon pay disabling these 3 Amazon Extension will result in normal email sending for Order Emails.

I have not tested if this issue has been fixed in 2.2.5 as since applying the update the Amazon Extensions remain disabled.

**Comment by jaredchu** [comment]
I tried to disable Ebizmarts_Mandrill in Magento backend and the order email is sending OK now. 
I'm looking forward to an official solution.

**Comment by Flipmediaco** [comment]
I found that with Ebizmarts_Mandrill disabled email transport started working for Order emails but the from address was not the address configured in Magento, it was [website user]@[isp host name] - this is far from ideal as the customer reply to address is not correct. 

The issue I suspect is the Amazon module is introducing a format error in the from address header. In the case of Mandrill it refuses to send the email due to this returning "Invalid Sender", in the case of your servers SMPT is simply defaults to the site user / host.

See: https://github.com/magento/magento2/issues/14952

To resolve disabled Amazon, via command line in site document root run:-

php -d memory_limit=-1 ./bin/magento module:disable Amazon_Payment
php -d memory_limit=-1 ./bin/magento module:disable Amazon_Login
php -d memory_limit=-1 ./bin/magento module:disable Amazon_Core
php -d memory_limit=-1 ./bin/magento module:enable Ebizmarts_Mandrill

Then clear cache, deploy static content etc...

**Comment by jaredchu** [comment]
@Flipmediaco it worked, thank you so much for your help!!!

**Comment by Flipmediaco** [comment]
This issue relates directly to the Amazon Pay module and I am therefore closing this. Hopefully the solution will help others until the Amazon Pay bug is resolved.

**Comment by josh-carter** [comment]
Seeing this happening on Magento 2.2.7 without Amazon modules installed. 

Anyone else getting this? 

Looks as though they've [changed some stuff with the TransportBuilder in 2.2.7](https://github.com/magento/magento2/compare/2.2.6...2.2.7#diff-dfb3ee5a7f863458afea75f5524cd2e5)

**Comment by Flipmediaco** [comment]
Mandrill stopped working as soon as we upgraded to Magento 2.2.7

Amazon modules remain disabled on this site

Any other feedback on this would be great - seen how I am stuck a double whammy of M1 patch error.

**Comment by gonzaloebiz** [comment]
Hi @Flipmediaco @josh-carter 

can you try applying the associated commit? https://github.com/ebizmarts/magento2-mandrill/commit/1368bcfe4a473d8e25a56a8214721054ec241b5b

Best

**Comment by josh-carter** [comment]
@gonzaloebiz @Flipmediaco Yep - can confirm its working again with that commit, thanks @gonzaloebiz

**Comment by dzierzega** [comment]
I have the same issue aftter upgrading magento to version 2.2.7
When we can expect the offical fix?

**Comment by DigitalStartupUK** [comment]
Thank you @gonzaloebiz for the commit. You saved me a headache. I don't suppose you've heard when your commit make make it into an official release?

**Comment by gonzaloebiz** [comment]
Will try next week

**Comment by davesims11** [comment]
@gonzaloebiz We seem to be having the same problem when trying to send emails out that has been mentioned above, have added the patch from the commit for now, but when will this be part of the official release?

**Comment by srenon** [comment]
@gonzaloebiz ... did you merge this in the latest release?

**Comment by gonzaloebiz** [comment]
@srenon 

you have a new version 3.2.17 including this fix
