### ISSUE TITLE
Customer receiving same order email twice after placing an order

### ISSUE THREAD

**Issue by jessyloran5** [ebizmarts/magento2-mandrill#77]
**Describe the bug**
We are using mandrill version 3.0.13 and Magento 2 version 2.2.5. Customers are getting same order email twice after placing an order.

**To Reproduce**
1. Go to product detail page
2. Click on add to cart
3. Place an order
4. Customer getting two confirmation order emails.

**Expected behavior**
Customer should only get one order confirmation email

**Screenshots**
![download](https://user-images.githubusercontent.com/41420637/43940284-875d774a-9c8c-11e8-8ed8-7a298f16511a.png)

![order-email](https://user-images.githubusercontent.com/41420637/43940952-b31df8ac-9c8f-11e8-8760-c8498479f290.png)

**Additional context**
Magento 2 version 2.2.5
Mandrill version 3.0.13

**Comment by lfritsche** [comment]
I've experienced the same behaviour, but without using mandrill. No solution found yet.
Also using M 2.2.5

**Comment by gonzaloebiz** [comment]
Hi @jessyloran5 

can you please see in the Mandrill site if the two email were sent by Mandrill? you can see it in the outbound 

Best

**Comment by gonzaloebiz** [comment]
Hi @lfritsche 

this repo is only for Mandrill issues, i think you are in the wrong site.

Best

**Comment by GBCtrading** [comment]
Hi @gonzaloebiz,

Yes mandrill showing multiple emails sent to customer.

https://drive.google.com/file/d/1pE00NJiqUuZigQ1rZbTVLNH63kmBVP7j/view?usp=drivesdk

![outbound activity _ mandrill](https://user-images.githubusercontent.com/41420349/45817723-48dd2380-bcfd-11e8-94a7-65c95dd5f8ad.png)

**Comment by gonzaloebiz** [comment]
If you have magento 2.2.* please update to the version 3.1.0

Best

**Comment by GBCtrading** [comment]
@gonzaloebiz , We have already updated to 3.1.0. But same issue. And this issue is only with order confirmation emails.

**Comment by gonzaloebiz** [comment]
Hi @GBCtrading 

we can't replicate as per yours indications.
I think your better approach is using other smtp service to test if really is a bug from mandrill extension or a bug in other part of your installation.

Best
