### ISSUE TITLE
Magento 2.2.6  Multistore application - Not sending emails in all stores

### ISSUE THREAD

**Issue by anupwankhede** [ebizmarts/magento2-mandrill#79]
**Application Environment:**
Magento => 2.2.6
ebizmarts/magento2-mandrill => 3.1.0
mailchimp/mc-magento2 => 1.0.29
ebizmarts/pos => 3.2.8

**Issue:**
While extension is working fine in Magento 2.1 application, its failing with following issue in Magento 2.2 application:
As said we have multi-store setup & this is working fine for only one store & failing in all other stores.

When I click on Send Email button in admin order view, it shows You sent the order email. message but do not send email and seeing following error in system.log :
/////////////////////////////////
[2018-09-10 09:25:10] main.ERROR: You must specify a key value [] []
////////////////////////////////

Nothing in exception.log though. var/Mailchimp folder is also empty.

Not getting this error for a store where its sending email successfully.

Please find attached configuration screenshot for a store for which it's failing to send an email.

![mandrill-magento-config](https://user-images.githubusercontent.com/5965276/46136488-53e80480-c265-11e8-8ca2-ff90a8ee7623.png)

**Comment by centerax** [comment]
could not replicate.
on which scope is the key entered?

**Comment by anupwankhede** [comment]
Hi @centerax , I did raise ticket with support as below:
Your request (17362) has been received and is being reviewed by our support staff.

Please check it for more details. I did not get reply on that since Sep 21.

**Comment by centerax** [comment]
Ok, lets keep the conversation on the ticket then.
