### ISSUE TITLE
Mandrill issue with subscriber

### ISSUE THREAD

**Issue by dexterityzx** [ebizmarts/magento2-mandrill#8]
I found that whenever I installed Mandrill module, the subscription function will fail. I will show “Something went wrong with the subscription.” And I track the code and found it threw an exception from sendConfirmationRequestEmail(). Can you check this? Thank you.

**Comment by gonzaloebiz** [comment]
You have the mandrill/mandrill lib installed?
Try run

composer require mandrill/mandrill

Best

**Comment by maderlock** [comment]
This looks like it might be the same issue as #10

**Comment by SantiParagarino** [comment]
Hello,

Sorry for the delay. This is solved for the latest version of the extension.
