### ISSUE TITLE
Cannot use Magento\Framework\Object as Object

### ISSUE THREAD

**Issue by pratikkamani** [ebizmarts/magento2-mandrill#84]
**Describe the bug**
Fatal error: Cannot use Magento\Framework\Object as Object because 'Object' is a special class name in /app/code/Ebizmarts/Mandrill/Controller/Adminhtml/Email/Test.php on line 13

Issue while setup:di:compile

**Comment by centerax** [comment]
what magento version? please use the bug report template and complete it fully.

**Comment by pratikkamani** [comment]
Magento version 2.3.0

**Comment by centerax** [comment]
what module version have you installed?

**Comment by pratikkamani** [comment]
Ebizmarts_Mandrill 3.0.7

**Comment by syedsaleem086** [comment]
@centerax Same issue here

```
Compilation was started.
%message% 0/7 [>---------------------------]   0% < 1 sec 68.5 MiB%message% 0/7 [>---------------------------]   0% < 1 sec 68.5 MiBProxies code generation... 0/7 [>---------------------------]   0% < 1 sec 68.5 MiB
Proxies code generation... 1/7 [====>-----------------------]  14% < 1 sec 72.5 MiB
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 72.5 MiBPHP Fatal error:  Cannot use Magento\Framework\Object as Object because 'Object' is a special class name in /var/www/html/saxon/releases/20190222011208/vendor/ebizmarts/magento2-mandrill/Controller/Adminhtml/Email/Test.php on line 13 [] []
```

**Comment by gonzaloebiz** [comment]
Use the right version https://github.com/ebizmarts/magento2-mandrill/releases/tag/3.3.15

**Comment by syedsaleem086** [comment]
> Use the right version https://github.com/ebizmarts/magento2-mandrill/releases/tag/3.3.15

@gonzaloebiz 

Same issue here please check the output of 
`composer show | grep mandrill`

```
ebizmarts/magento2-mandrill                                       3.3.15    Connect Mandrill with Magento
mandrill/mandrill                                                 1.0.55    API client library for the Mandrill email as a service platform
```

![image](https://user-images.githubusercontent.com/15724424/53283101-3ad97600-3767-11e9-856e-a0d3de6d94bb.png)

**Comment by nhudson76** [comment]
http://php.net/manual/en/reserved.other-reserved-words.php

mage dropped the ball in allowing framework to require php:~7.2

**Comment by 234146326** [comment]
`use Magento\Framework\Object;`

I have this class in my theme module.

When I compiled, it reported this kind of error.

Has the problem of the landlord been solved?Thanks Reply.
@centerax @gonzaloebiz @pratikkamani @syedsaleem086 @nhudson76

**Comment by gonzaloebiz** [comment]
What version of magento and mandrill are you using?
