### ISSUE TITLE
Fatal error on Setting production mode in Magento2.3.0

### ISSUE THREAD

**Issue by syedsaleem086** [ebizmarts/magento2-mandrill#89]
**Describe the bug**
Compilation failed on Magento2.3.0

**To Reproduce**
1. Install Magento2.3.0
2. Install Mandrill Extension using composer
3. PHP7.2-FPM

```
Compilation was started.
%message% 0/7 [>---------------------------]   0% < 1 sec 68.5 MiB%message% 0/7 [>---------------------------]   0% < 1 sec 68.5 MiBProxies code generation... 0/7 [>---------------------------]   0% < 1 sec 68.5 MiB
Proxies code generation... 1/7 [====>-----------------------]  14% < 1 sec 72.5 MiB
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 72.5 MiBPHP Fatal error:  Cannot use Magento\Framework\Object as Object because 'Object' is a special class name in /var/www/html/saxon/releases/20190222011208/vendor/ebizmarts/magento2-mandrill/Controller/Adminhtml/Email/Test.php on line 13 [] []
```

**Expected behavior**
Should complete the compilation without error

**Comment by gonzaloebiz** [comment]
Hi @syedsaleem086 

thanks for your feedback,
What version of ebizmarts/magento2-mandrill do you have? (you can run composer show | grep mandrill to know)

Best

**Comment by syedsaleem086** [comment]
Hi @gonzaloebiz Please check the output of
`composer show | grep mandrill`
```
ebizmarts/magento2-mandrill                                       3.3.15    Connect Mandrill with Magento
mandrill/mandrill                                                 1.0.55    API client library for the Mandrill email as a service platform

```

![image](https://user-images.githubusercontent.com/15724424/53283064-a5d67d00-3766-11e9-8d43-e26e0d4c1bcd.png)

**Comment by undert03** [comment]
getting the same and here is my out put

ubuntu@:~/magento2$ composer show | grep mandrill     
ebizmarts/magento2-mandrill                                 3.3.15    Connect Mandrill with Magento
mandrill/mandrill                                           1.0.55    API client library for the Mandrill email as a service platform

**Comment by undert03** [comment]
as a side note i have the mailchimp module installed by you too. not sure if it's related

**Comment by undert03** [comment]
Edited Test.php with your changes it it worked just fine. Thanks!
