### ISSUE TITLE
Bugs: Wrong argument data type after saved $apiKey

### ISSUE THREAD

**Issue by thuydx** [ebizmarts/magento2-mandrill#9]
```
class Mandrill
{
    /**
     * @var \Mandrill
     */
    protected $_api;
    /**
     * Mandrill constructor.
     * @param \Ebizmarts\Mandrill\Helper\Data $helper
     */
    public function __construct(
        \Ebizmarts\Mandrill\Helper\Data $helper
    )
    {
        $apiKey     = $helper->getApiKey();
        if($apiKey!='') {
            $this->_api = New Mandrill($apiKey);
        }
    }
```

Recoverable Error: Argument 1 passed to Ebizmarts\Mandrill\Model\Api\Mandrill::__construct() must be an instance of Ebizmarts\Mandrill\Helper\Data, string given, called in app/code/Ebizmarts/Mandrill/Model/Api/Mandrill.php on line 31 and defined in app/code/Ebizmarts/Mandrill/Model/Api/Mandrill.php on line 27

**Comment by gonzaloebiz** [comment]
Hi @thuydx 

thanks for your feedback
Can you specify how to reproduce it?

Best

**Comment by thuydx** [comment]
Login to admin side.
Stores >> Configuration >> MageMonkey >> Mandrill 

Enabled: Yes
API Key:  your-api-key
....
After save config that error appeared 
When I debug: 

```
$apiKey     = $helper->getApiKey();   
\\ return the api-key "your-api-key"
\\ That is string
$this->_api = New \Mandrill($apiKey);      \\ <~~ Need \Ebizmarts\Mandrill\Helper\Data instance
```

Please recheck when have data saved to db

**Comment by avra911** [comment]
I am getting:

```
Fatal error: Class 'Mandrill' not found in /home/claudiu/htdocs/tillskottsbolaget/app/code/Ebizmarts/Mandrill/Model/Api/Mandrill.php on line 31```

R

**Comment by gonzaloebiz** [comment]
Hi @thuydx 

i just try with magento 2.0.7 and works fine.
What version of ebizmarts/magento2-mandrill do you have?
