### ISSUE TITLE
Remove unused extension functionality

### ISSUE THREAD

**Issue by arendarenko** [ebizmarts/magento2-mandrill#97]
**Preconditions**
Module version - 3.2.17
Magento 2 Version - 2.2.7

**Describe the bug**
I found several controllers in frontend-area which probably is not used anymore: https://github.com/ebizmarts/magento2-mandrill/tree/2.2-develop/Controller/Autoresponder because block, which returns Lists for Autoresponder contans stub-method: https://github.com/ebizmarts/magento2-mandrill/blob/d3bc2543459fa4e1e59aa4e2eedf028c9dee356c/Block/Customer/Account/Autoresponder/View.php#L21

Also looks like tables, which created by module is also never used in code:
* mandrill_templates
* mandrill_mailsent
* mandrill_unsubscribe

**To Reproduce**
See bug description.

**Expected behavior**
Frontend area code should be used or deleted.
Module shouldn't create tables which is doesn't used in it's code.

**Additional context**
When customer goes to url mandrill/autoresponder/view, he receives exceptions:

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Ebizmarts\Mandrill\Block\Customer\Account\Autoresponder\View::__
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Ebizmarts\Mandrill\Block\Customer\Account\Autoresponder\View::__
#0 [internal function]: Magento\Framework\DataObject->__call('__', Array)

**Comment by gonzaloebiz** [comment]
Thanks @alexeya-ven

**Comment by arendarenko** [comment]
Hi @gonzaloebiz 
thanks for fixing it.
How about tables 

mandrill_templates
mandrill_mailsent
mandrill_unsubscribe

Looks like they aren't used too. Maybe we should remove them too?
