### ISSUE TITLE
Error: Extra parameters passed to parent construct in /mandrill/Model/SenderBuilder.php

### ISSUE THREAD

**Issue by arendarenko** [ebizmarts/magento2-mandrill#98]
**Preconditions**
1. Magento 2 version - 2.2.7
2. Module version - 3.2.17

**Describe the bug**
After module install during DI compile receiving such error: 

Extra parameters passed to parent construct: $transportBuilderByStore. File: %path%/vendor/ebizmarts/magento2-mandrill/Model/SenderBuilder.php

**To Reproduce**
1. Install module
2. Run DI compile console command

**Expected behavior**
There is no errors during DI compile

**Additional context**
Original constructor contains 3 parameters: 
* Template $templateContainer,
* IdentityInterface $identityContainer,
* TransportBuilder $transportBuilder

Module passes 4 paremeters: 
* $templateContainer
* $identityContainer
* $transportBuilder
* $transportBuilderByStore

**Comment by gonzaloebiz** [comment]
Hi @alexeya-ven 

thanks for your feedback.
Please take a look

![image](https://user-images.githubusercontent.com/6222792/54443897-65906c00-4720-11e9-8bf9-2e7de23d962d.png)

The compilation is OK for me.
Any other particular setting?

Best
